CAPTURE_TOPIC = 'capture'
BOT_START = '%s.B1'%(CAPTURE_TOPIC)
BOT_END = '%s.B2'%(CAPTURE_TOPIC)
MOUSE_START = '%s.M1'%(CAPTURE_TOPIC)
MOUSE_END = '%s.M2'%(CAPTURE_TOPIC)
KEY_START = '%s.K1'%(CAPTURE_TOPIC)
KEY_END = '%s.K2'%(CAPTURE_TOPIC)